Resources:
  staticContent:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-${self:provider.stage}-static
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  backup:
    Type: AWS::S3::Bucket
    Properties:
        BucketName: ${self:service}-${self:provider.stage}-backup

  cvTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-cvs
      AttributeDefinitions:
        - AttributeName: trigram
          AttributeType: S
        - AttributeName: experienceId
          AttributeType: S

      KeySchema:
        - AttributeName: trigram
          KeyType: HASH
        - AttributeName: "experienceId"
          KeyType : RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
